# Используем официальный образ Python
FROM python:3.13-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY gateway.py .

# Указываем команду для запуска
CMD ["uvicorn", "gateway:app", "--host", "0.0.0.0", "--port", "8000"]